### ISSUE TITLE
Change API server default publishing strategy for NONE platforms

### ISSUE THREAD

**Issue by nirarg** [openshift/hypershift#1009]
Currently, in **Kubevirt**, **Agent** and **None** platforms, the API server is created with NodePort publishing strategy.

For production environments, the Nodeport publishing strategy can't be used, and for those cases we can have the assumption that the management OCP cluster supports LoadBalancer. 
I want to change  the default publishing strategy to LoadBalancer and to add specific flag (--nodeport-publish-strategy) to keep the ability to use nodeport, for development use cases.

I tested this with **Kubevirt** platform, on management cluster installed on libvirt VMs, I installed **MetalLB** on the cluster to have the LoadBalancer support.

@avishayt @eranco74 do you have any objection to have this change also for the **Agent** platform?

**Comment by enxebre** [comment]
>For production environments, the Nodeport publishing strategy can't be used

why?

**Comment by nirarg** [comment]
> > For production environments, the Nodeport publishing strategy can't be used
> 
> why?

There is no guaranty that the specific node used for the IP is always running, it might stop running unexpectedly
We can require that the management cluster support LoadBalancer, user can install MetalLB operator on the management cluster in order to support this

**Comment by nirarg** [comment]
It was decided to start only with Kubevirt platform,  if it ever made sense we could expand it to other platforms
