### ISSUE TITLE
Security: Control Plane Components should not automount service tokens if not required 

### ISSUE THREAD

**Issue by relyt0925** [openshift/hypershift#1028]
Our control plane security requires that cluster master pods not automount service acount tokens unless absolutely necessary. Here's the current list of security violations when compared to a non-Hypershift deployment of ROKS version 4.9.

vagrant@verify-cluster:~$ for DEPLOYMENT in $(kubectl get deployments -n master-prtesting49-63493628 -o name); do
>     echo "${DEPLOYMENT} automountServiceAccountToken: $(kubectl get "${DEPLOYMENT}" -n master-prtesting49-63493628 -o jsonpath='{.spec.template.spec.automountServiceAccountToken}')" | grep -vE 'false|cluster-health|cluster-updater|control-plane-operator|etcd-operator|openvpn-operator|rbac-sync-operator'
> done
deployment.apps/catalog-operator automountServiceAccountToken: 
deployment.apps/certified-operators-catalog automountServiceAccountToken: 
deployment.apps/cluster-api automountServiceAccountToken: 
deployment.apps/cluster-autoscaler automountServiceAccountToken: 
deployment.apps/cluster-policy-controller automountServiceAccountToken: 
deployment.apps/community-operators-catalog automountServiceAccountToken: 
deployment.apps/hosted-cluster-config-operator automountServiceAccountToken: 
deployment.apps/ignition-server automountServiceAccountToken: 
deployment.apps/machine-approver automountServiceAccountToken: 
deployment.apps/olm-operator automountServiceAccountToken: 
deployment.apps/packageserver automountServiceAccountToken: 
deployment.apps/redhat-marketplace-catalog automountServiceAccountToken: 
deployment.apps/redhat-operators-catalog automountServiceAccountToken:

**Comment by sjenning** [comment]
This sgtm.  Anyone that has time can proceed with this.  If you are working on this, please post here so we don't dup effort.

**Comment by michael-topchiev** [comment]
Out of the list above, based on initial testing, the following components likely do not need auto-mount service tokens:
- catalog-operator
- certified-operators-catalog
- cluster-policy-controller
- community-operators-catalog
- redhat-marketplace-catalog
- redhat-operators-catalog
- olm-operator
