### ISSUE TITLE
Ensure control plane roll out adheres to Kubernetes version skew policy

### ISSUE THREAD

**Issue by hasueki** [openshift/hypershift#1222]
Need to ensure that the roll out of control plane components (kube-apiserver, kube-controller-manager, kube-scheduler, etc) on upgrades adheres to the [supported upgrade order](https://kubernetes.io/releases/version-skew-policy/#supported-component-upgrade-order) described under the Kubernetes version skew policy.

On upgrades, CPO will need to make sure all new instances of `kube-apiserver` is fully rolled out and ready, before reconciling `kube-controller-manager`, `kube-scheduler`, `cloud-controller-manager` deployments.

**Comment by rtheis** [comment]
Do the OpenShift components have similar upgrade order restrictions as they related to each other or Kubernetes that need to be addressed as well?

**Comment by hasueki** [comment]
@csrwng do you happen to have any insights regarding Richard's comment above ^?
