### ISSUE TITLE
Proposal: restructure the HostedCluster AWS role API spec

### ISSUE THREAD

**Issue by ironcladlou** [openshift/hypershift#1297]
This is a proposal to refactor the [HostedCluster.Spec.Platform.AWS.Roles](https://github.com/openshift/hypershift/blob/main/api/v1alpha1/hostedcluster_types.go#L777) API field to clarify the contract per  [HOSTEDCP-153](https://issues.redhat.com/browse/HOSTEDCP-153).

One way of restructuring could be:

```go
type AWSPlatformSpec struct {
	Roles AWSRoles `json:"roles"`
}

// ARN is an AWS ARN value
type ARN string

type AWSRoles struct {
	// IngressOIDC references a role used for TODO
	//
	// The following is an example of a valid policy document:
	//
	// {
	//	"Version": "2012-10-17",
	//	"Statement": [
	//		{
	//			"Effect": "Allow",
	//			"Action": [
	//				"elasticloadbalancing:DescribeLoadBalancers",
	//				"tag:GetResources",
	//				"route53:ListHostedZones"
	//			],
	//			"Resource": "*"
	//		},
	//		{
	//			"Effect": "Allow",
	//			"Action": [
	//				"route53:ChangeResourceRecordSets"
	//			],
	//			"Resource": [
	//				"arn:aws:route53:::PUBLIC_ZONE_ID",
	//				"arn:aws:route53:::PRIVATE_ZONE_ID"
	//			]
	//		}
	//	]
	// }
	IngressOIDC ARN `json:"ingressOidc"`
	
	// TODO
	ImageRegistryOIDC ARN `json:"imageRegistryOidc"`
	
	// TODO
	StorageOIDC ARN `json:"storageOidc"`
	
	// TODO
	NetworkOIDC ARN `json:"networkOidc"`
}
```

This eliminates the leakage of internal details about the underlying secrets the values are actually used for, while also providing a more direct opportunity to document each field with details about the expected contents of the role behind each ARN reference (for example, by putting a literal example of a valid policy document in the field docs).

Thoughts?

**Comment by csrwng** [comment]
Sounds good to me, just a nit: we may want to suffix the fields with `Role` instead of `OIDC`

**Comment by ironcladlou** [comment]
Do we have any compatibility issues to consider for this?

**Comment by csrwng** [comment]
AFAIK no, but we should double check with the ACM team
