### ISSUE TITLE
ROKS Requirements for Hypershift

### ISSUE THREAD

**Issue by csrwng** [openshift/hypershift#130]
Requirements:

- [ ] Authentication for MCO
- [ ] NodePort services in control plane
- [ ] Adopt cluster/byo etcd/pki

### Current
Machine Config server has no authentication and anyone that has network access to the server can download sensitive cluster payload 

### Solution:
Will add a haproxy sidecar that verifies a token url parameter that corresponds to the node-bootstrapper-token in the cluster. Machines in their boot user-data will specify this token and be able to fetch the payload. Controllers will be in place for when the token is rotated to update the user-data payload and haproxy config to reference new token automatically.

### Current
Hypershift relies on services of type LoadBalancer for vpn and kube api and routes for oauth and ignition

### MVP Solution:
Ability to publish all services using node ports 

#### Exit criteria:
All external services exposed as a node port which include:

```
kube-apiserver          NodePort  172.21.217.92  <none>    	2040:31320/TCP  	39h
machine-config-server   NodePort  172.21.95.205  <none>    	80:31249/TCP        39h
konnectivity            NodePort  172.21.55.150  <none>    	1194:31250/TCP  	39h
oauth-openshift         NodePort  172.21.162.205 <none>    	443:31251/TCP       39h
```

### Long term (ignore for this year):
Utilize SNI https://en.wikipedia.org/wiki/Server_Name_Indication and unique domain names per cluster per exposed service to be able to route everything through only port 443 using ISTIO

#### Example
konnectivity-clusterid1.SUBDOMAIN -> istio/router -> backend service TLS passthough
apiserver-clusterid1.SUBDOMAIN -> istio/router -> backend service TLS passthough
oauth-clusterid1.SUBDOMAIN -> istio/router -> backend service TLS passthough

and deploy config that will tell the router component to send TLS to these endpoints.

#### Benefit: 
Customers will only need to expose 443 to the set domain name 
All ingress traffic comes through single point of entry that can enable advanced audit log use cases 

### Current:
In automation upstream etcd operator is deployed and a single replica etcd cluster is deployed as well

### Requirement: 
Need to be able to seamlessly "adopt" all the existing ROKS clusters we have in production to be under hypershift control

One key difference: etcd clusters are named differently in ROKS and automation deploys etcd-operator/the etcd cluster. All backup/restore/operations associated with etcd depend on this system. 

### Example:  
named etcd-CLUSTERID. All services correspond to that name as well
```
kubectl get etcdcluster -n master-bvnqi2710tsfq5mqtbrg
NAME                        AGE
etcd-bvnqi2710tsfq5mqtbrg   68d
```

We will also create the downstream PKI secrets that integrate into our CA rotation system.

**Comment by csrwng** [comment]
@openshift/team-hypershift-maintainers this issue is to track the requirements for ROKS on hypershift and to contain any discussion/questions that come from them. 
@relyt0925 created this issue from your document. So we can minimize churn with your PRs, let's discuss how we want to solve the problems here and then update the PRs appropriately.

**Comment by relyt0925** [comment]
You got it sir!

**Comment by relyt0925** [comment]
@csrwng how would you like to go about working a potentially solution for node port support. That was from this PR:
https://github.com/openshift/hypershift/pull/89

**Comment by csrwng** [comment]
Definitely, let's tackle the NodePort one first. Some questions that I still had about it are:
- Does it make sense for it to be a per-cluster thing or should it be a global operator config type of thing (whether to use NodePort or LoadBalancer type services)? Do we foresee a single management cluster allowing both NodePort and LoadBalancer type services? Does the hostname vary per child cluster within a single management/tugboat cluster?
- If you are using NodePort, will you always use the same host for everything the cluster needs to expose? or should we allow for a separate host for apiserver vs vpn vs mco, etc?
- Do you ever want to be able to specify which NodePort to use for each service or is the one randomly assigned by kube ok?

**Comment by relyt0925** [comment]
My perspective:
1) In practice: I forsee for the vast majority of time one strategy in action: The only caveat I would add is if I was trying to predict the future I do foresee the potential on a version update of ROKS (aka 4.9 to 4.10 or whatever) of clusters moving to a different strategy if a better one is developed in the future. Like for example new capabilities lead to a want to move from a node port based strategy to a new strategy. I do not forsee that being load balancers though and would be a different publishing strategy. Maybe something like SNI in the future for all components. MVP for sure one strategy per management cluster though

2)  If we are using a node port: it will all be over the same host. I think that's a reasonable assumption as well as the main idea of this strategy is all traffic across nodeports is multiplexed over the same hostname endpoints for scaling purposes.

3) On the initial adoption we will *need* to be able to keep our existing node ports that's critical. Currently: we do an initial random assigning and then they stay constant from there on out. We have no need to control the initial node port assigning just that it remains the same once assigned for the life of the cluster.

**Comment by csrwng** [comment]
@relyt0925 it sounds like what @ironcladlou had [suggested](https://github.com/openshift/hypershift/pull/89#discussion_r591990394) should be good enough, with the addition that we want to optionally allow specifying the port numbers, like:
```go
type HostedCluster struct {
	// ...
	PublishingStrategy ControlPlanePublishingStrategy
}

type ControlPlanePublishingStrategy struct {
	Type ControlPlanePublishingStrategyType `json:"type"`

	LoadBalancer *LoadBalancerPublishingStrategy `json:"loadBalancer,omitempty"`

	NodePort *NodePortPublishingStrategy `json:"nodePort,omitempty"`
}

type NodePortPublishingStrategy struct {
	Host string
	ServicePorts []ServicePortMapping
}

type ServicePortMapping struct {
	Service ServiceNameType // where this is an enum of KubeAPI, VPN, etc
	Port int32
}
```
@openshift/team-hypershift-maintainers ^^

@relyt0925 I do want to understand the adoption case a little better. So far it's been fairly straightforward to think of hypershift as something managing new clusters, but I do see the need to transition existing clusters to something managed by hypershift as they upgrade. So it would require that etcd be preserved as well as port numbers for external services. Anything else?

**Comment by relyt0925** [comment]
That's a fantastic question @csrwng 

In general: it needs to maintain all "per cluster" config that you would expect to be maintained across an update boundary. Tangibly what that means in our case is basically the current state of the cluster (enabled features/ existing certs/ etc) need to be taken into the automation and not destroyed.

At a very basic level from my perspective that is:
- Certs/keys/PKI infrastructure
- Pod CIDRs and Service CIDRS
- Apiserver advertised addresses
- Apiserver secure port
- Cluster Service IPs/names

The above is at a general base openshift level. Now I will touch on more IBM Specific use cases which will lead into why we view "Asset payload control" as important

Customers in our offering can enable disable various "configurations" like
- API Audit webhook configurations
- KMS/Encrypting Secret data at rest: https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/
- Existing IBM Cloud Oauth server IAM integration/configuration
- Cloud Provider Configuration
- Portieris configuration

There is then more config that is mainly for deployment topology/ reliability purposes. These are mainly labels, affinity rules, tolerations, CPU/Mem limits/requests, and readiness/liveness probes on the various pods that spread out the HA workload (3 replicas) across zones, hosts, etc. And scope specific types of workload to specific nodes. But the main idea is preserving the key componentry outlined in the previous two sections.

**Comment by relyt0925** [comment]
@csrwng refactored PR up

**Comment by relyt0925** [comment]
Refactor #2 is here: 
https://github.com/openshift/hypershift/pull/163

**Comment by relyt0925** [comment]
closing this one in favor of more specific issues
