### ISSUE TITLE
Security: olm-collect-profiles should not have access to all secrets in namespace

### ISSUE THREAD

**Issue by hasueki** [openshift/hypershift#1347]
Currently, the `olm-collect-profiles` service account binds a role that gives it read and update access to all secrets in the control plane namespace. 
https://github.com/openshift/hypershift/blob/b32f090daae4ecadaf747f8b548ec104fc4e1f65/control-plane-operator/controllers/hostedcontrolplane/olm/assets/olm-collect-profiles.role.yaml

This component should only have access to the `pprof-cert` secret as seen in its source.
https://github.com/openshift/operator-framework-olm/blob/5d74cef25c663ff581abdb87fa1a94fe7a222144/cmd/collect-profiles/main.go#L320

**Comment by alvaroaleman** [comment]
Fixed in https://github.com/openshift/hypershift/pull/1349
/close
