### ISSUE TITLE
Propagate TLS security profile config to kube-controller-manager and kube-scheduler

### ISSUE THREAD

**Issue by hasueki** [openshift/hypershift#1371]
In HyperShift, TLS security profiles are configurable for OCP control plane components via the `kind: APIServer` definition from the [cluster configuration](https://github.com/openshift/hypershift/blob/main/docs/content/how-to/cluster-configuration.md) items in the HostedCluster.

Currently, the TLS security profile (CipherSuites and MinTLSVersion) gets honored for the below components:
- kube-apiserver
- oauth-openshift
- openshift-apiserver
- openshift-controller-manager

..but not for:
- kube-controller-manager
- kube-scheduler

**Comment by alvaroaleman** [comment]
Fixed in https://github.com/openshift/hypershift/pull/1388
/close
