### ISSUE TITLE
Ensure caching performed (and binary verification) for pulled mco binaries

### ISSUE THREAD

**Issue by relyt0925** [openshift/hypershift#1437]
Currently in this path:
https://github.com/relyt0925/hypershift/blob/main/ignition-server/controllers/local_ignitionprovider.go#L207-L208

there is no caching performed when pulling the release image for a given nodePool to generate the ignition data. This means that extra calls have to be made to the registry whenever any change or restart happens to an ignition pod. 

Instead: we should cache the image we pull and ensure the cache is indexed based off the "mco image" or a hash of the mco image. Then we should check the cache to see if the binaries exist before calling to the registry. We should additionally perform binary verification (for example: potentially running a help command to ensure the binary is not corrupted) before deeming it a cache hit. If the verification fails or there are no files in that cache location: we should proceed to repull the files from the registry and then populate the cache.

Locking needs to be performed around updating the cache (read write lock). This will optimize load on the backend registry that is used.

**Comment by enxebre** [comment]
@relyt0925 wouldn't/shouldn't this be handle by the registry client?

**Comment by relyt0925** [comment]
@enxebre I think there are multiple solutions that are all valid: my main focus is just on the ultimate goal that the registry traffic is reduced to only making pulls when necessary

**Comment by michael-topchiev** [comment]
The enhancement is implemented, this issue can be closed.
