### ISSUE TITLE
Support disabling of go profiling for control plane components

### ISSUE THREAD

**Issue by hasueki** [openshift/hypershift#1438]
We should disable go profiling for `kube-apiserver`, `kube-controller-manager`, and `kube-scheduler` to follow security best practices highlighted in [CIS benchmark for Kubernetes](https://www.cisecurity.org/benchmark/kubernetes) and [this Red Hat blog](https://cloud.redhat.com/blog/12-kubernetes-configuration-best-practices). It would be a matter of setting `--profiling=false` on these containers.

For IBM Cloud, we need to make sure profiling is disabled to meet requirements highlighted in https://cloud.ibm.com/docs/openshift?topic=openshift-cis-benchmark-410

**Comment by hasueki** [comment]
After discussion, we will want the option to disable go profiling for any platform, as well as the flexibility to disable it for any control plane component.

The proposed design is to support a new annotation on the `HostedCluster`/`HostedControlPlane` that will set a string value of a comma-delimited list of "services", or components, to disable profiling on.
```
hypershift.openshift.io/disable-profiling=kube-apiserver,kube-controller-manager,kube-scheduler
```

**Comment by a-dsouza** [comment]
Findings from trying to implement support for disabling profiling for all control plane components:
`clusterpolicy` `cvo` `configoperator` `oauth` `oapi` and `ocm` aren't set to recognize the profiling flag. Upon trying to set profiling to false, all these components experience failures. 
`etcd` and `konnectivity` both have a flag to enable profiling, but profiling is disabled as default. 
As per the CIS Benchmark requirements, `kcm` `kas` and `scheduler` will have the option to disable profiling if included in the annotation for `HostedCluster`/`HostedControlPlane`.
