### ISSUE TITLE
LoadBalancer created by Cloud Controller Manager (CCM) is not getting cleaned up when the cluster is deleted.

### ISSUE THREAD

**Issue by dharaneeshvrd** [openshift/hypershift#1439]
**Observation:**

- Currently when we create and delete the hypershift cluster, below is the observation,
- Hypershift cluster is created with hypershift cli. Control plane components are set up and running,`service` named `router-default` of type `LoadBalancer` is created in `openshift-ingress` namespace on deployed cluster, CCM creates an external load balancer in the respective cloud for ingress purpose. 
- This LoadBalancer will get deleted only when `service router-default` is deleted by CCM.
- When we delete the cluster by deleting the hosted cluster, everything getting cleaned up on the deployed cluster and control plane components deployed in management cluster in hosted cluster namespace is getting deleted.
- But external LoadBalancer is not getting cleaned with the above process. (possible reason could be API server might become unreachable to CCM to check the `service router-default` 's status or it might have died during the clean up of management cluster's hosted cluster namespace - **Need more exploration here**).

**Comment by mkumatag** [comment]
I'm wondering what happens in the other platforms like AWS? Can we quickly check if it is getting cleaned up? if yes - how?

**Comment by dharaneeshvrd** [comment]
In AWS case also, LB is not getting cleaned when we delete the hosted cluster. 
Could not figure out which component is responsible for create and delete LB in AWS case, since CCM is not involved.

**Comment by mkumatag** [comment]
> In AWS case also, LB is not getting cleaned when we delete the hosted cluster.
> Could not figure out which component is responsible for create and delete LB in AWS case, since CCM is not involved.

They have in-tree cloud-provider code handling this

**Comment by alvaroaleman** [comment]
Fixed in #1672 
/close
