### ISSUE TITLE
Failed to create control plane pods on disconnected cluster

### ISSUE THREAD

**Issue by nadavdolin** [openshift/hypershift#1452]
hello,
I try to create a hypershift + kubevirt cluster on disconnected cluster.
i stuck on the stage when on the new namepsace cluster have the 4 pods:
capi-provider, cluster-api, control-plane-operator and ignition-server
after that it need to create more pods for the control plane but it didn't happend.
i don't see any log in the control-plane-operator pod that can help me.
infra OCP version: 4.9.12
cluster version that i try to up: 4.10.11

Thanks!

**Comment by rgolangh** [comment]
@nadavdolin please provide also the hypershift image version or at least the operator digest.

**Comment by csrwng** [comment]
@nadavdolin can you tell whether there were any failures to pull images in the control plane namespace? (a list of events in that namespace may help)

**Comment by nadavdolin** [comment]
The new version of hypershift is fix the problem, Thanks!
