### ISSUE TITLE
Support configuring private endpoint publishing for ingress controller

### ISSUE THREAD

**Issue by hasueki** [openshift/hypershift#1599]
We would like the ability to configure ingress controller with endpoint publishing strategy as [Private](https://github.com/openshift/api/blob/dab5b363ebd164329cca439552339470b2b14ef8/operator/v1/types_ingress.go#L761).

After discussion, we will expose this configuration setting as an annotation on the `HostedCluster`/`HostedControlPlane` CRs. And will be generic to be applicable for any providers.

The annotation itself may look something like..
```
hypershift.openshift.io/private-ingress-controller=true
```

**Comment by pcrentsil** [comment]
Refer to --> https://github.com/openshift/hypershift/pull/1597/files

For up-to-date PR regarding this issue.
