### ISSUE TITLE
additional trusted-bundle CA into the vm not work

### ISSUE THREAD

**Issue by nadavdolin** [openshift/hypershift#1615]
Hello,
I have some issues with hypershift.
I run a hypershift+kubevirt on a disconnected cluster
when the cluster tries to up everything is run well my one problem is that I add for the `hypershift create cluster kubevirt` command the flag: `--additional-trusted-bundle` and he takes it well and creates a configMap with the name `user-ca-bundle` and the pods know to use it but I need it for the VM's too. so I research when the problem is and I found that the pod `ignition-server` need to add this CA to the payload and the VM uses it as ignition, but I don't see the CA in the payload.

infra OCP version: 4.10.16
cluster version that i try to up: 4.10.16

what more information i can provide to help you help me :)
Thanks!

**Comment by alvaroaleman** [comment]
/assign @hardys 
Can you look into this?

**Comment by nadavdolin** [comment]
Hey @alvaroaleman,I add PR that fix the bug you can look at this #1633
