### ISSUE TITLE
Issue in PowerVS cluster deletion cleanup - ingresscontroller cleanup

### ISSUE THREAD

**Issue by dharaneeshvrd** [openshift/hypershift#1738]
Trying to delete powervs cluster with clean up flag `--destroy-cloud-resources`. Where deletion is stuck on ingress-operator on deleting the dnsrecords.

While making GET or POST API to IBM Cloud to retrieve dnsrecord list, getting `EOF` or `net/http: TLS handshake timeout`

`"error": "delete: failed to list the dns record: An error occurred while performing the 'authenticate' step: Post \"https://iam.cloud.ibm.com/identity/token\": EOF", "errorCauses": [{"error": "delete: failed to list the dns record: An error occurred while performing the 'authenticate' step: Post \"https://iam.cloud.ibm.com/identity/token\": EOF"}, {"error": "delete: failed to list the dns record: An error occurred while performing the 'authenticate' step: Post \"https://iam.cloud.ibm.com/identity/token\": EOF"}]`

Few points to note:
1. Not facing this issue on plain destroy without the clean up flag.
2. Not facing this issue in AWS cluster deletion with the cleanup flag.
3. While the cluster is up deleting the dnsrecord is working fine. Tried deleting the default dnsrecord of default ingress controller, able to see its getting recreated in both guest cluster as well as in IBM Cloud CIS.

Adding IBM Cloud endpoints to `NoProxy` env var solves the problem. 
But not sure why it's not happening in AWS case.

**Comment by dharaneeshvrd** [comment]
@csrwng If you could provide any input on this issue, that would be so helpful.

cc @mkumatag

**Comment by alvaroaleman** [comment]
AWS and Azure cloud apies are no_proxied for the ingress controller through this: https://github.com/openshift/hypershift/blob/d3bdf54708eb47a5a655121d546fe089cb663de3/konnectivity-socks5-proxy/main.go#L179

I believe @relyt0925 did explicitly not want that for IBM cloud, but I might misremember. cc @hasueki
