### ISSUE TITLE
Hosted control plane is missing cluster ingress configuration

### ISSUE THREAD

**Issue by ironcladlou** [openshift/hypershift#215]
A new hosted control plane's `ingresses.config.openshift.io/cluster` resource has an empty `.spec.domain` value. This breaks the ability to create a hosted cluster within a hosted cluster because the OIDC endpoint can't be discovered as a function of the cluster ingress domain.

This is a regression introduced by https://github.com/openshift/hypershift/pull/196.

**Comment by ironcladlou** [comment]
I think this manifest is missing entirely from the control plane operator, but I haven't looked too closely yet.

**Comment by sjenning** [comment]
yeah, installer creates this
https://github.com/openshift/installer/blob/6d778f911e79afad8ba2ff4301eda5b5cf4d8e9e/pkg/asset/manifests/ingress.go#L80-L95

**Comment by sjenning** [comment]
we are creating the IngressController but not the top level global ingress config
https://github.com/openshift/hypershift/blob/main/control-plane-operator/controllers/hostedcontrolplane/assets/cluster-bootstrap/cluster-ingress-02-config.yaml

**Comment by sjenning** [comment]
should be fixed by https://github.com/openshift/hypershift/pull/216
