### ISSUE TITLE
MVP: Customize Network Type Configuration

### ISSUE THREAD

**Issue by relyt0925** [openshift/hypershift#223]
We need the ability to control the network type used here:
https://github.com/openshift/hypershift/blob/73da1bc576c46d5a45f440a79b3b17717f5a3243/control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go#L795

The immediate use case is for IBM Cloud Openshift clusters Calico is utilized as the SDN provider. 

Acceptance Critieria:
- [ ] Support the ability to configure different NetworkTypes for hypershift clusters

**Comment by relyt0925** [comment]
the initial MVP support for this is done future work streams can be opened in a follow up issue (like the OVN-Kubernetes one)

**Comment by aravindhp** [comment]
@relyt0925 @enxebre where should I be opening up follow up issues to track customizing network type configuration?
