### ISSUE TITLE
Release HyperShift CLI binaries on merge

### ISSUE THREAD

**Issue by Roming22** [openshift/hypershift#2234]
To consume the hypershift cli binary (in the users' devenv, or in an image), one has to install go, clone the repository and build the binary.
It would be easier to consume a pre-built binary from the repository.

**Comment by abdennour** [comment]
Even though, it's not straightforward to build it. From my side, it never build: 

```log
docker run -it --rm -v $(pwd):/code -w /code golang:1.18 make build
CGO_ENABLED=0 GO111MODULE=on GOFLAGS=-mod=vendor go build -gcflags=all='-N -l' -o bin/hypershift-operator ./hypershift-operator

# k8s.io/kube-openapi/pkg/cached
vendor/k8s.io/kube-openapi/pkg/cached/cache.go:242:16: undefined: atomic.Pointer
make: *** [Makefile:72: hypershift-operator] Error 2
```

**Comment by Roming22** [comment]
/remove-lifecycle stale

Any chance this could be done?
Pinging a random fellow Red Hatter: @davidvossel
