### ISSUE TITLE
capi-provider - ImagePullBackOff

### ISSUE THREAD

**Issue by itmwiw** [openshift/hypershift#2250]
Hi,
I'm trying to install a hypershift cluster with Kubevirt as a provider. 
Everythings works fine apart from the capi-provider. The capi-provider pod can't pull the docker image. Here's what I get in the events: 
```
Failed to pull image "registry.ci.openshift.org/ocp/4.13:cluster-api-provider-kubevirt": rpc error: code = Unknown desc = reading manifest cluster-api-provider-kubevirt in registry.ci.openshift.org/ocp/4.13: unauthorized: authentication required
```
I tried both the operator's version 4.12 and 4.13
I got my pullsecret from here: https://console.redhat.com/openshift/install/platform-agnostic/user-provisioned
Can you help me please?
Thanks in advance.
Regards,
Tarik

**Comment by ppeereb1** [comment]
We run into the same issue.

**Comment by stianfro** [comment]
We are having the same issue:

```
Back-off pulling image "registry.ci.openshift.org/ocp/4.15:cluster-api-provider-kubevirt"
```

/reopen
