### ISSUE TITLE
RHCOS MVP: IBM Cloud VPC Gen 2 cluster-api machine controller integration

### ISSUE THREAD

**Issue by relyt0925** [openshift/hypershift#231]
We need the ability to deploy/configure the appropriate cluster-api machine controller depending on the cloud provider. This involves deploying the machine controller and the appropriate CRDs/config that this controller will read. 

Acceptance Criteria:
- [ ] Support deploying the IBM Cloud VPC Gen 2 cluster-api machine controller when deploying into IBM Cloud VPC Gen 2 environments.
- [ ] Ensure dependent config/CRDs also configured and deployed as well to support the machine controller. 
- [ ] Define pluggable architecture that can be extended for future cloud providers.

**Comment by gyliu513** [comment]
@relyt0925 does this project can  help https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud , this is for VPC Gen V2 Support.
