### ISSUE TITLE
GA Operations: Pod affinity based off clusterid

### ISSUE THREAD

**Issue by relyt0925** [openshift/hypershift#235]
We need to be able to specify pod affinity rules based off a given clusterID to ensure various master components prefer to run colocated on a given node in a given zone. This helps isolate the affect that a given cluster can have on other components running on separate nodes. It also helps optimize the communication path between cluster components since they prefer to be colocated on a given node.

Configuration in ibm-roks-toolkit:
https://github.com/openshift/ibm-roks-toolkit/blob/ec875b0243ac58d095a3eec840ee4d09c24995c2/assets/kube-apiserver/kube-apiserver-deployment.yaml#L34

Acceptance Criteria: 
- [ ] Ability to specify affinity rules for manifests of hypershift clusters.

**Comment by ironcladlou** [comment]
Design was https://github.com/openshift/hypershift/issues/370 and is now tracked in https://issues.redhat.com/browse/HOSTEDCP-194
