### ISSUE TITLE
GA Operations: Toleration specification on master component manifests

### ISSUE THREAD

**Issue by relyt0925** [openshift/hypershift#237]
We need the support to specify tolerations on the master component manifests. This allows taints to be used in the management cluster to isolate specific types of workload to help prevent certain noisy neighbor problems and allow for special use cases where larger clusters need dedicated machines to support the amount of traffic/workload being processed in the cluster.

The configuration in ROKS toolkit is here: https://github.com/openshift/ibm-roks-toolkit/blob/ec875b0243ac58d095a3eec840ee4d09c24995c2/assets/kube-apiserver/kube-apiserver-deployment.yaml#L28

Acceptance Criteria:
- [ ] Ability to specify tolerations on master component manifests.

**Comment by ironcladlou** [comment]
Design was https://github.com/openshift/hypershift/issues/371 and now tracked in https://issues.redhat.com/browse/HOSTEDCP-193
