### ISSUE TITLE
GA Operations: Priority class specification

### ISSUE THREAD

**Issue by relyt0925** [openshift/hypershift#238]
We need the ability to specify priority classes on critical master deployment manifests in order to ensure these manifests do not get evicted when the workers they are on enter disk pressure, memory pressure, etc. This allows lower priority workload to get evicted first before the master components are considered for eviction.

IBM Roks configuration: https://github.com/openshift/ibm-roks-toolkit/blob/ec875b0243ac58d095a3eec840ee4d09c24995c2/assets/kube-apiserver/kube-apiserver-deployment.yaml#L59

Acceptance Criteria:
- [ ] Ability to specify priority classes on master component manifests

**Comment by ironcladlou** [comment]
Resulted in https://github.com/openshift/hypershift/issues/377 and tracked now in https://issues.redhat.com/browse/HOSTEDCP-191
