### ISSUE TITLE
secret "service-network-admin-kubeconfig" not found cause capi-provider to not continue cluster creation

### ISSUE THREAD

**Issue by giacomotontini** [openshift/hypershift#2428]
I'm trying to deploy a single node cluster (single worker) on AWS cloud, while keeping the control plane pods on a OS cluster hosted locally on our company datacenter. Hosted cluster has ACM installed (version 2.7.2) with multiclusterengine enabled (version 2.2.2) through OperatorHub.

Command used (executed successfully):
```
hypershift create cluster aws 
  --name $CLUSTER_NAME 
  --node-pool-replicas=1 
  --secret-creds $AWS_CREDS 
  --region $REGION 
  --network-type OVNKubernetes 
  --generate-ssh 
  --namespace multicluster-engine 
  --instance-type m5.xlarge
  ```
  
  Cause within `capi-provider-6cdc7775d4-72nsd` pod 
`  MountVolume.SetUp failed for volume "svc-kubeconfig" : secret "service-network-admin-kubeconfig" not found `
And consequently
`Unable to attach or mount volumes: unmounted volumes=[svc-kubeconfig], unattached volumes=[token svc-kubeconfig kube-api-access-w7rw6 credentials capi-webhooks-tls]: timed out waiting for the condition
`  

That's the view from acm of the creating cluster

![image](https://user-images.githubusercontent.com/42031947/232019283-70355d41-5baf-4e76-98d8-bba21c93478c.png)

I've also noticied that the kube-apiserver deployment is completely missing.
The container `availability-prober`  within capi-provider-6cdc7775d4-72nsd pod  is continuosly trying to connect to a missing kube-apiserver.

**Comment by rokej** [comment]
@giacomotontini Can you please provide the status condition of the hosted cluster CR?
