### ISSUE TITLE
Determine control plane metric integration system

### ISSUE THREAD

**Issue by relyt0925** [openshift/hypershift#261]
I was curious if that's still planned in hypershift. Didn't see it getting deployed yet so will change this issue into tracking deploying that if we plan on still using it

**Comment by KodieGlosserIBM** [comment]
IBM ROKS Toolkit ROKS-Metrics deployment
https://github.com/openshift/ibm-roks-toolkit/tree/master/assets/roks-metrics

**Comment by relyt0925** [comment]
Design doc in process:
https://coreos.slack.com/files/U9TF68JS3/F02JZCQPTJN/hypershift_-_guest_cluster_metrics

**Comment by rtheis** [comment]
https://github.com/openshift/enhancements/pull/981/files#diff-ff45e6a60a1567f4e77f0a2f64354afe284ff5a10f270fe7935182b59a15c68dR189-R198
