### ISSUE TITLE
Failed to create cluster

### ISSUE THREAD

**Issue by gitmedur** [openshift/hypershift#2658]
Hi,
Running hypershift with OCP 4.13.1. With the latest version compiled hypershift  client, when I submit:
hypershift create cluster kubevirt --name $KUBEVIRT_CLUSTER_NAME --node-pool-replicas=2 --memory '8Gi' --pull-secret $PULL_SECRET --release-image=quay.io/openshift-release-dev/ocp-release@sha256:9c92b5ec203ee7f81626cc4e9f02086484056a76548961e5895916f136302b1f 

I'm getting:
2023-06-07T16:15:05+03:00       INFO    Applied Kube resource   {"kind": "Namespace", "namespace": "", "name": "clusters"}
2023-06-07T16:15:05+03:00       INFO    Applied Kube resource   {"kind": "Secret", "namespace": "clusters", "name": "kv1-pull-secret"}
2023-06-07T16:15:05+03:00       INFO    Applied Kube resource   {"kind": "", "namespace": "clusters", "name": "kv1"}
2023-06-07T16:15:05+03:00       INFO    Applied Kube resource   {"kind": "Secret", "namespace": "clusters", "name": "kv1-etcd-encryption-key"}
2023-06-07T16:15:05+03:00       ERROR   Failed to create cluster        {"error": "failed to apply object \"clusters/kv1\": failed to create typed patch object (clusters/kv1; hypershift.openshift.io/v1beta1, Kind=NodePool): .spec.arch: field not declared in schema"}
github.com/spf13/cobra.(*Command).execute
        /go/hypershift/vendor/github.com/spf13/cobra/command.go:916
github.com/spf13/cobra.(*Command).ExecuteC
        /go/hypershift/vendor/github.com/spf13/cobra/command.go:1044
github.com/spf13/cobra.(*Command).Execute
        /go/hypershift/vendor/github.com/spf13/cobra/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext
        /go/hypershift/vendor/github.com/spf13/cobra/command.go:961
main.main
        /go/hypershift/main.go:70
runtime.main
        /usr/local/go/src/runtime/proc.go:250
Error: failed to apply object "clusters/kv1": failed to create typed patch object (clusters/kv1; hypershift.openshift.io/v1beta1, Kind=NodePool): .spec.arch: field not declared in schema
failed to apply object "clusters/kv1": failed to create typed patch object (clusters/kv1; hypershift.openshift.io/v1beta1, Kind=NodePool): .spec.arch: field not declared in schema

The pods are getting up in the clusters-$KUBEVIRT_CLUSTER_NAME project.
Somehow, followed this guidance getting things up in OpenShift ->  https://cloud.redhat.com/blog/effortlessly-and-efficiently-provision-openshift-clusters-with-openshift-virtualization

Will you please guide m?
Thanks

**Comment by gitmedur** [comment]
Just got back to release-4.13 version for hypershift and seems it's working..
fyi.

**Comment by aabouzaid** [comment]
I had the same issue. As a workaround, I passed `--render` and saved the manifests to a file, then removed the `.spec.arch` from `NodePool` manifest. And it worked.

Hypershift CLI version:
```
openshift/hypershift: 7b7089020d494a8cdd4d10645df7adcbeef48941. Latest supported OCP: 4.14.0
```

OpenShift cluster version: `4.13.4`

**Comment by alcamie101** [comment]
@aabouzaid could you give the steps and commands that you took to make this work please, if you still remember? I'm having a hell of a time hitting this constantly.

**Comment by aabouzaid** [comment]
@alcamie101 just use the same command and add `--render` (it's like `helm template` or kubectl dry-run), then save the output in a file and remove that key (you can also use `jq` to remove it on the fly).
