### ISSUE TITLE
GA Operations: Remove need for log connections in operations

### ISSUE THREAD

**Issue by relyt0925** [openshift/hypershift#266]
I do not believe we want to rely on logs/exec in critical operations for reliability purposes. Currently it is a requirement for the imageLookup pod:
https://github.com/openshift/hypershift/blob/fec57f340bbc2133218fdf134c1a9685bb90e866/control-plane-operator/releaseinfo/pod_provider.go#L81-L85

Opening this for a tracker to see how we can either move to configmaps/ a different system.

**Comment by ironcladlou** [comment]
Tracked in https://issues.redhat.com/browse/HOSTEDCP-196
