### ISSUE TITLE
MVP: secure kubelet serving/client cert approving system (remove auto approver)

### ISSUE THREAD

**Issue by relyt0925** [openshift/hypershift#279]
We just need a more secure strategy around approving csrs.

Cluster machine config operator handles that in Openshift today: https://github.com/openshift/cluster-machine-approver

There's options to do an IBM specific implementation as well if this doesn't ultimately fit into hypershift.

**Comment by relyt0925** [comment]
I think an acceptable solution here is to look at the active machines through cluster-api and approve if the machines ip exists in the list.

**Comment by relyt0925** [comment]
We are going with the machine approver from openshift. If that turns out to be a large effort we can consider a fallback strategy.

**Comment by enxebre** [comment]
we are running the machine approver now
/close
