### ISSUE TITLE
Proposal: ignition server abstraction

### ISSUE THREAD

**Issue by ironcladlou** [openshift/hypershift#303]
# Ignition server abstraction proposal

## Problem

The current ignition mechanism presents some challenges:

- As new NodePool versions are noticed and new MCS versions rolled out in response, it's tricky to try and ensure instances at any given version (old or new) will ignite from the right underlying MCS backend. This complexity seems to be in part because a single MCS backend is responsible for ignition of all NodePool versions.
- The ignition proxy has to make assumptions about the nodepool MCS endpoint using intrinsic knowledge of implementation details (the service name of a NodePool's Machine Config Server, aka MCS). This coupling became a problem when trying to secure the MCS with TLS, as the proxy would need updated to connect to a qualified domain name for the MCS service (which will include a <namespace>.svc suffix).
- All NodePools for a HostedCluster share an authz token, increasing the blast radius of a token leak
- Ignition clients must request a dynamically generated path associated with a nodepool when a static URL and opaque token is all that is really necessary.
- Managing *N* ignition servers per cluster for this purpose is a lot of moving parts given the task of serving static bytes, increasing the bug surface area.

Building from the the discussion in #297 and prior conversations about simplifying ignition generally, this proposal is to stop managing long-lived Machine Config Servers (MCS) entirely and promote the ignition proxy to be the authoritative ignition server and solve the above problems in doing so.

## Goals

- Eliminate the need to deal with any timing concerns or rollout gating behaviors to given multiple versions of NodePools which might require ignition to be served concurrently during rollouts.
- Scope tokens to NodePool instead of HostedCluster.
- Eliminate the need to actively reconcile/manage MachineConfigServers.
- Simplify ignition client setup by removing dynamic elements (e.g. dynamic request path requirements).

## Proposal

Today the ignition-server component of the hypershift-operator is a proxy to multiple MCS backends. The premise of the solution is to expand the responsibilities of the ignition-server component to become the self-contained authoritative ignition server itself, and changing the role of MCS to be an implementation detail of the ignition server.

### nodepool-controller

The nodepool-controller currently manages MCS deployments which act as backends to the ignition-server proxy, which itself is managed by hostedcluster-controller. The hostedcluster-controller also manages token generation. In this proposal, nodepool-controller is redesigned to:

- Lose all knowledge of Machine Config Servers (e.g. deployments, services, RBAC, etc.)
- Assume responsibility for reconciling an ignition secret for each NodePool; the structure being:

    ```yaml
    type: Secret
    metadata:
      labels:
        hypershift.io/ignition-config: "true"
    data:
      token: <authz token>
      version: <version string>
    ```

  This secret's contents are basically a simple config interface to the ignition server and represent the inputs used to generate ignition contents and handle authorization.
- Assume responsibility for handling deletions of stale ignition secret entries.
- Configure the ignition userdata secret for instances to a static `/` path for ignition requests.

### hostedcluster-controller

The hostedcluster-controller currently manages a single auth token used to configure the ignition server covering all NodePools for the HostedCluster. In this proposal, hostedcluster-controller is redesigned to:

- Lose all knowledge of ignition auth tokens; this responsibility now belongs to the nodepool-controller.
- Manage additional resources to enable the ignition server's execution environment to account for its new permissions requirements (e.g. a service account, role, role binding, etc.)

### ignition-server

The ignition-server currently proxies requests to MCS backends and authenticates based on a token configured from the hostedcluster-controller. In this proposal, ignition-server is changed significantly to:

* Gain a Kubernetes client with permissions to read secrets in the hosted control plane namespace.
* Read ignition secrets and maintain an internal map of tokens to ignition payload bytes so that it can serve requests directly without proxying to MCS instances (which no longer exist in the proposed model).

Internally, ignition-server will abstract the MCS behind a new interface used to transform HostedCluster/NodePool inputs (i.e. the ignition secret contents) to ignition payload bytes:

```go
// IgnitionProvider can build ignition payload contents
// for a given release version.
type IgnitionProvider interface {
  // GetPayload returns the ignition payload contents for
  // the provided release version. In the future the list of
  // inputs may expand to incorporate user-provided ignition
  // overlay contents.
  GetPayload(version string) []byte
}
```

The initial implementation will be backed by MCS pods.

```go
// MCSPodIgnitionProvider is an IgnitionProvider that uses
// MachineConfigServer pods to build ignition payload contents.
//
// TODO: Describe in more detail how this works (similar to the
// release image lookup mechanism.)
type MCSPodIgnitionProvider struct {
  // ...
}
```

The ignition-server uses the ignition secrets and `IgnitionProvider` interface to handle request routing and serving. Pseudo-code:

```
// A map of authz token to ignition payload contents
payloads = map[string]bytes

// Build ignition and routing data by reading cluster state. This
// happens periodically or in response to watch events.
func reconcilePayloads() {
  // ignitionConfigSecrets is all secrets in the current namespace
  // with the `hypershift.io/ignition-config` label.
  for each secret in ignitionConfigSecrets {
    token = secret["token"]
    version = secret["version"]
    payload = ignitionProvider.GetPayload(version) 
    payloads[token] = payload
  }
}

// Request handling is handled in terms of `configs`
func handle(request, response) {
  token = getToken(request)
  payload, hasPayload = payloads[token]
  if hasPayload {
    // authorized, write payload to response
  } else {
    // not authorized, or invalid
  }
}
```

No path-based routing is necessary.

**Comment by relyt0925** [comment]
From an IBM perspective we will need to be able to control payloads from day 1 (just saw a comment where in the future that would be supported). Or we still need the ability to stay on the current design until that support lands.
