### ISSUE TITLE
GA Operations: (Scalability) Optimize load induced on management cluster API Server

### ISSUE THREAD

**Issue by relyt0925** [openshift/hypershift#306]
Our perf squad after running with 440 clusters for a couple days noticed the API Server of the management cluster is repeatedly getting OOMKilled:
![Screen Shot 2021-06-21 at 12 59 38 PM](https://user-images.githubusercontent.com/7716924/122807015-ac228880-d290-11eb-8985-c19c160e78a1.png)

**Comment by relyt0925** [comment]
management cluster master components  were on 
16 core 64 gig dedicated machines.
3 master components running in each AZ (one per AZ).
Etcd was also on a dedicated 16 core 64 gig machine with one instance running in each AZ

**Comment by relyt0925** [comment]
The current ratio we have in production is 
116 nodes per zone * 3 zones = 348 nodes (dedicated 16 core 64 gig machines)
440 clusters (cluster components have instances in multiple AZs).

so that is a 1.26 cluster per node density on average.

**Comment by relyt0925** [comment]
Currently at 54 hosted clusters
![Screen Shot 2021-07-30 at 8 00 43 AM](https://user-images.githubusercontent.com/7716924/127656585-78fbb6f4-c53c-41bd-bf64-1d5a4b5dd044.png)

**Comment by relyt0925** [comment]
The growing lines are the kube-apiserver containers the rest are all the other containers in the system.

**Comment by relyt0925** [comment]
However: Things do appear to be stabilizing and if anything I am seeing the larger jumps correspond *not* to more management clusters but instead to adding more worker nodes into the cluster to hold the hosted control plane componets

An example of this is shown below:
![Screen Shot 2021-08-01 at 5 15 37 PM](https://user-images.githubusercontent.com/7716924/127786869-26154b43-8d27-48f0-9aed-30baeb56ff44.png)

**Comment by relyt0925** [comment]
That time of increase was actually corresponding to when I scaled the cluster from a total of 120 nodes to 225 nodes. The rest of the graph is when I scaled from 82 to 175 hostedclusters. In that time I see no significant uptick trends of memory utilization of API Servers.

**Comment by relyt0925** [comment]
[pprofresults_30plusGB_afterrestart.zip](https://github.com/openshift/hypershift/files/6940672/pprofresults_30plusGB_afterrestart.zip)

**Comment by relyt0925** [comment]
![Screen Shot 2021-08-05 at 2 01 50 PM](https://user-images.githubusercontent.com/7716924/128406437-114fd811-01c5-407e-89d1-41c41c720ed9.png)

**Comment by relyt0925** [comment]
![Screen Shot 2021-08-05 at 2 04 45 PM](https://user-images.githubusercontent.com/7716924/128406775-258bd507-0d82-445b-8df1-662e5bf2c67b.png)
![Screen Shot 2021-08-05 at 2 04 20 PM](https://user-images.githubusercontent.com/7716924/128406778-aafe081a-6846-4bde-aaea-3a901b2395e3.png)
![Screen Shot 2021-08-05 at 2 04 08 PM](https://user-images.githubusercontent.com/7716924/128406779-b9c7d106-18d7-41ab-944f-1c31ef205f46.png)
![Screen Shot 2021-08-05 at 2 03 57 PM](https://user-images.githubusercontent.com/7716924/128406782-b869640e-de2c-4486-81f3-dc19224d3d05.png)
![Screen Shot 2021-08-05 at 2 03 47 PM](https://user-images.githubusercontent.com/7716924/128406784-d47a5ddc-a5ea-45fd-93b3-716881ffc656.png)

**Comment by relyt0925** [comment]
Secrets then spikes extremely large (1.4K watch requests) which seems really large

**Comment by relyt0925** [comment]
after that flux things seem to stabilize:
![Screen Shot 2021-08-05 at 2 07 07 PM](https://user-images.githubusercontent.com/7716924/128407092-37dde4a5-610d-49bb-a775-9192752e3867.png)

**Comment by relyt0925** [comment]
nothing major on the controller side of things during this time:
![Screen Shot 2021-08-05 at 2 11 12 PM](https://user-images.githubusercontent.com/7716924/128407573-28cbecfa-c9cb-4df5-9134-10e8136ed98b.png)

**Comment by relyt0925** [comment]
Dropping 
--default-watch-cache-size to 33 significantly helps the load (default is 100)

**Comment by relyt0925** [comment]
![Screen Shot 2021-08-05 at 10 49 41 PM](https://user-images.githubusercontent.com/7716924/128453346-fa8006ce-b003-4e24-b4d9-1ca13b66eb97.png)

**Comment by derekwaynecarr** [comment]
@sttts @deads2k any thoughts on optimal tuning of api-server to handle a thundering herd of re-establishing watch connections?

**Comment by deads2k** [comment]
> @sttts @deads2k any thoughts on optimal tuning of api-server to handle a thundering herd of re-establishing watch connections?

We added a patch in 4.8 to address the infinite concurrency of watchers in prior releases.  We noticed it for clusters with many kubelets and pods trying to rewatch lots of secrets.  The change charges watchers during the establishment of their watch connections, so it improves cases where many watchers all attempt to watch at the same time.  It does not improve cases of wide fanout when an update to a single secret is observed by a large number of watchers.

The PR (linked to the upstream that landed in  1.22) is https://github.com/openshift/kubernetes/pull/773.

@tkashem if you have more comments.

**Comment by relyt0925** [comment]
thank you for this @deads2k !

**Comment by tkashem** [comment]
> any thoughts on optimal tuning of api-server to handle a thundering herd of re-establishing watch connections?

in addition to openshift/kubernetes#773, on the management cluster you can add a new priority & fairness rule to set a  concurrency limit for these watch requests (watch initialization only). 

Also, the default values for `max-requests-inflight` and `max-mutating-requests-inflight` are too high for the management cluster, since the management cluster is managed by us, i would recommend lowering these values as well (depending on the number of cpu cores the master node has) 
https://github.com/openshift/cluster-kube-apiserver-operator/blob/master/bindata/assets/config/defaultconfig.yaml#L117-L121

**Comment by relyt0925** [comment]
Running performance tests with updates as well......

**Comment by rgschofield** [comment]
https://github.com/openshift/multus-admission-controller/issues/40

We've also raised the above issue that highlights instabvilities following kube-apiserver restarts that are triggered by the multus admisson controller running on each node in the management cluster.
