### ISSUE TITLE
GA: Pass Zonal failure test

### ISSUE THREAD

**Issue by relyt0925** [openshift/hypershift#350]
we should run a test of shutting down an entire AZ of a management cluster running hypershift components and see if it passes failure testing. Any gaps should be closed before GA.

**Comment by ironcladlou** [comment]
We'll track this as QE for multi-zonal spread (https://issues.redhat.com/browse/HOSTEDCP-195)

**Comment by relyt0925** [comment]
Note: IBM will still need to perform and pass it's zonal failure test suite.
