### ISSUE TITLE
Support externalTrafficPolicy: Local in LoadBalancerPublishingStrategy 

### ISSUE THREAD

**Issue by freedge** [openshift/hypershift#3592]
```hypershift create cluster kubevirt``` renders spec:
```
  - service: APIServer
    servicePublishingStrategy:
      type: LoadBalancer
```
that ends up creating a service having
```
  externalTrafficPolicy: Cluster
```

It would be great if it could be Local instead, so that the traffic is routed to the right node
https://metallb.universe.tf/usage/#local-traffic-policy-1

**Comment by davidvossel** [comment]
>It would be great if it could be Local instead, so that the traffic is routed to the right node
https://metallb.universe.tf/usage/#local-traffic-policy-1

Yes, I see how that could benefit the Agent platform.

I'm unsure if the KubeVirt platform would benefit much from this though. In that case, the bulk of the api server traffic is going to come from the VMs acting as worker nodes  which in most cases will result in internal traffic. Per the externalTrafficPolicy documentation, that internal traffic would default to Cluster even if we set it to Local.

```
Note that traffic sent to an External IP or LoadBalancer IP from within the cluster will always get "Cluster" semantics
```
