### ISSUE TITLE
RHCOS MVP: Support dynamic Ignition data on reconcile loop 

### ISSUE THREAD

**Issue by KodieGlosserIBM** [openshift/hypershift#386]
When making changes or adding ignition data configmaps the ignition pod should be able to detect changes and dynamically add them on the reconcile loop without the pod needing to restart. 

Current reconciliation loop is here: https://github.com/openshift/hypershift/blob/4fc9a8e2c9ecbabc9b1671b4c55951bae6cb019e/ignition-server/controllers/tokensecret_controller.go#L142

We can possibly look to adding something to detect changes as this part when generating the payload.

**Comment by relyt0925** [comment]
Think it'll be solved in this PR:
https://github.com/openshift/hypershift/pull/357/files
