### ISSUE TITLE
Z/Power Prototyping: Nodepool architecture specification

### ISSUE THREAD

**Issue by relyt0925** [openshift/hypershift#400]
There is one thing that the multiarch manifest won't be able to solve: and that is selecting the initial image to use to bootup the RHCOS machines on the power/Z architecture. Prototypes will need to be done on how that is used to lookup an image from a different documented release stream:
https://github.com/openshift/installer/blob/release-4.8/data/data/rhcos-ppc64le.json#L48

And then used in the provisioning engine that the cluster-api plugin provides in for the provider the Power/Z team is targeting

**Comment by jwcroppe** [comment]
@mkumatag FYI

**Comment by mkumatag** [comment]
For the cloud scenario now, RHCOS pipeline is created to publish the powervs compatible images to the COS bucket and also updated the [rhcos.json](https://github.com/openshift/installer/blob/3f318d7049d5f4b6f98211b4b899fdb43b1f3542/data/data/coreos/rhcos.json#L247:L307) file.

and also we have the patch in the hypershift code to read the content via https://github.com/openshift/hypershift/pull/690, we can use these images for the vm deployment via CAPI.

**Comment by mkumatag** [comment]
We have added the support for the PoweVS platform support into the hypershift project and [this code](https://github.com/openshift/hypershift/blob/eba1271e46123b5f528438dbda14383e5f3213d9/hypershift-operator/controllers/nodepool/powervs.go#L78:L91) fetches the right image from the rhcos spec and used for the vm deployments.
