### ISSUE TITLE
Z/Power Prototyping: Ensuring cluster-api provider properly designed for IAAS system they will be using

### ISSUE THREAD

**Issue by relyt0925** [openshift/hypershift#401]
A cluster-api plugin needs to be written that will be used to automate ordering/deleting (CRUD operations) of the machines in a given IAAS provider. Some examples today:
https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud
https://github.com/kubernetes-sigs/cluster-api-provider-aws
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere

The team needs to examine for whatever infra layer they are using (an IAAS APIs) that the system exists today that can properly integrate with those apis and provision machines, delete machines, etc

**Comment by clnperez** [comment]
FYI - as we're working on IPI support for Power VS, we have created https://github.com/openshift/cluster-api-provider-powervs

FYI @mkumatag ^

**Comment by jwcroppe** [comment]
Thanks @clnperez ... this should tackle this piece for provisioning into Power Virtual Server (PowerVS) for off-prem deployments.  We'll still need to explore IPI for PowerVC for on-prem, but that'll be the second phase.

/cc @relyt0925

**Comment by mkumatag** [comment]
For the PowerVS platform we have added support to - https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud

**Comment by jwcroppe** [comment]
> For the PowerVS platform we have added support to - https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud

Great work, @mkumatag!  I'm wondering... do we want to track any other Power work here - or should we consider more granular issues that we can track/close?  

Thoughts @relyt0925?

**Comment by mkumatag** [comment]
For the powervs platform merged into the hypershift repository uses the code from the https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud and all the required changes are in the repository.
