### ISSUE TITLE
Fix gaps of monitoring probes on all components 

### ISSUE THREAD

**Issue by relyt0925** [openshift/hypershift#408]
Listing the few that don't have any livliness health checks 
```
operator (namespace: hypershift) livliness period 240 seconds. readiness period 30. Failure threshold 3 for each.
cluster-api - livliness period 240 seconds. readiness period 30. Failure threshold 3 for each.
cluster-autoscaler - livliness period 240 seconds. readiness period 30. Failure threshold 3 for each.
cluster-policy-controller - livliness period 240 seconds. readiness period 30. Failure threshold 3 for each.
cluster-version-operator - livliness period 240 seconds. readiness period 30. Failure threshold 3 for each.
control-plane-operator - livliness period 240 seconds. readiness period 30. Failure threshold 3 for each.
hosted-cluster-config-operator -livliness period 240 seconds. readiness period 30. Failure threshold 3 for each. 
kube-scheduler - livliness period 240 seconds. readiness period 30. Failure threshold 3 for each.
openshift-controller-manager - livliness period 240 seconds. readiness period 30. Failure threshold 3 for each.
```
livliness and readiness can use same endpoint if applicable (same http route)

Ideally there is some sort of continous monitoring on these to help ensure they are functioning overtime

**Comment by relyt0925** [comment]
Good ones to start with are operator, control-plane-operator, and hosted-cluster-config-operator

**Comment by relyt0925** [comment]
relevant code for operator:
https://github.com/openshift/hypershift/blob/main/cmd/install/assets/hypershift_operator.go#L122

relevant code for control-plane-operator:
https://github.com/openshift/hypershift/blob/main/hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go#L1837


relevant code for hosted-cluster-config-operator:
https://github.com/openshift/hypershift/blob/6411565039a5d696f6fd8e6113b57dc5bbe909e1/control-plane-operator/controllers/hostedcontrolplane/configoperator/reconcile.go#L160

(just for general pointers may need code changes elsewhere after testing)

**Comment by relyt0925** [comment]
Example code link to where to add livliness probe for hosted-cluster-config-operator:
https://github.com/openshift/hypershift/blob/main/control-plane-operator/controllers/hostedcontrolplane/configoperator/params.go#L42

And example livliness probe for kas:
https://github.com/openshift/hypershift/blob/main/control-plane-operator/controllers/hostedcontrolplane/kas/params.go#L153-L165

**Comment by michael-topchiev** [comment]
I do not see metrics or health endpoints in cluster-policy-controller and could not find them in its source code either (https://github.com/openshift/cluster-policy-controller). Adding the probes to cluster-policy-controller will probably require modifying cluster-policy-controller code.

**Comment by michael-topchiev** [comment]
cluster-version-operator does not have any listeners, neither for metrics nor for liveness/readiness probes. I do not see the probes its source code either (https://github.com/openshift/cluster-version-operator). Adding the probes to cluster-version-operator will probably require modifying cluster-version-operator code.

**Comment by relyt0925** [comment]
Remaining components without healthcheck
```
machine-approver 
openshift-controller-manager
cluster-version-operator
cluster-policy-controller
```

**Comment by relyt0925** [comment]
Remaining ones require more work and are 
```
openshift-controller-manager
cluster-version-operator
cluster-policy-controller
```

**Comment by relyt0925** [comment]
Additionally: Readinessprobes need to be specified on
```
deployment.apps/konnectivity-server readinessProbe:
deployment.apps/openshift-oauth-apiserver readinessProbe:
```

Since they are apart of a service.

**Comment by michael-topchiev** [comment]
> Additionally: Readinessprobes need to be specified on
> 
> ```
> deployment.apps/konnectivity-server readinessProbe:
> deployment.apps/openshift-oauth-apiserver readinessProbe:
> ```
> 
> Since they are apart of a service.

PR is submitted for these two components: https://github.ibm.com/alchemy-containers/sonar-squad/issues/142
