### ISSUE TITLE
Failed to install hypershift package

### ISSUE THREAD

**Issue by gyohuangxin** [openshift/hypershift#444]
I try to install hypershift with command:
```
go install github.com/openshift/hypershift@latest
```

But it failed with error message:
```
go install github.com/openshift/hypershift@latest: github.com/openshift/hypershift@v0.0.0-20210826030201-9e6982f7554e
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.

```
Go version: go1.16.7 linux/amd64

**Comment by tmishina** [comment]
Hi @ironcladlou, I faced same problem as @gyohuangxin.
Workaround would be using `go get`, but it also fails.

```
$ go get github.com/openshift/hypershift
go: downloading github.com/openshift/hypershift v0.0.0-20210831162544-c55a88107a53
go get: github.com/openshift/hypershift@none updating to
	github.com/openshift/hypershift@v0.0.0-20210831162544-c55a88107a53 requires
	sigs.k8s.io/cluster-api-provider-aws@v0.7.0 requires
	sigs.k8s.io/cluster-api/test@v0.4.1 requires
	sigs.k8s.io/cluster-api@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

Is there any other workaround? Which commit can I install the hypershift CLI without this error?

**Comment by ironcladlou** [comment]
Because we now use several `replace` directives in `go.mod` it's not obvious to me yet how to solve this. In the meantime, I recommend cloning the repo and running `make` to build the binaries. Will that suffice in the meantime?

**Comment by enxebre** [comment]
>Is there any other workaround? Which commit can I install the hypershift CLI without this error?

@tmishina As a workaround you can add a replace clause to your go.mod file
replace sigs.k8s.io/cluster-api => sigs.k8s.io/cluster-api v0.4.2

That you let go get succeed.

**Comment by tmishina** [comment]
@ironcladlou Thank you, I can successfully build the CLI by using `make`!

@enxebre In my understanding, the suggested line (`replace sigs.k8s.io/cluster-api => sigs.k8s.io/cluster-api v0.4.2`) has already been added in [this commit](https://github.com/openshift/hypershift/commit/c0eb13ce5ad24997ef886572d84afcae78787983#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R62).  Isn't this directive same as your suggestion?

**Comment by jan--f** [comment]
I also just ran into this.

Is it maybe worth updating https://github.com/openshift/hypershift/blob/71106752a4f2cc97ace5b56a752bce451fa1d613/docs/content/getting-started.md?plain=1#L21-L24 until either `go install` can handle this [scenario](https://github.com/golang/go/issues/44840) or the replace directives go away?
