### ISSUE TITLE
RHCOS inplace upgrade/join system (upi path) 

### ISSUE THREAD

**Issue by relyt0925** [openshift/hypershift#530]
We need to come to an agreement on the "base architecture" for UPI (user provisioned) infrastructure. Once the base is provided IBM will consider how to build on that base and integrate into the Satellite environment. This is  tracking coming up with the original design and then we will move forward with implementation issues

**Comment by relyt0925** [comment]
RedHat is still in the design phases of this. We will check back on the sync up this thursday

**Comment by relyt0925** [comment]
We are moving further on this:

The current idea is to utilize the Agent strategy (without utilizing the assisted installer).

Then the redhat team is meeting with the MCO folks for an MVP design on how to account for the MachineConfig and MachineConfigPool APIs that downstream operators rely on to configure machines.

**Comment by hardys** [comment]
> The current idea is to utilize the Agent strategy (without utilizing the assisted installer).

@relyt0925 do you have any more details on this?  It'd be great to consider if/how we might avoid long-term overlap with the assisted agent platform flow /cc @avishayt

**Comment by relyt0925** [comment]
@hardys this slack link might help with details (demo video of whole process):
https://coreos.slack.com/files/U015GA40J4E/F02T97WNPL4/rhcos_demo.zip

Strategy has been approved. closing
