### ISSUE TITLE
add resource requests to hypershift operator install and review to ensure all components have requests

### ISSUE THREAD

**Issue by relyt0925** [openshift/hypershift#650]
hypershift operator currently when getting installed does not set any resource requests. That should be done. In addition any other components should be scanned to see if they don't have any

**Comment by relyt0925** [comment]
Relevant code:
https://github.com/openshift/hypershift/blob/main/cmd/install/assets/hypershift_operator.go#L121

**Comment by hasueki** [comment]
Resource request specification should get added somewhere here, https://github.com/openshift/hypershift/blob/7039f790e959f7daab7234f45697b9f6f0fac017/cmd/install/assets/hypershift_operator.go#L155

API: https://github.com/kubernetes/api/blob/882d2ec6f15bb12af59722949736d9722a2afe47/core/v1/types.go#L2218

**Comment by jzielny** [comment]
https://github.com/openshift/hypershift/pull/970
