### ISSUE TITLE
Support a heterogeneous cluster using a multi-arch release image

### ISSUE THREAD

**Issue by moriohara** [openshift/hypershift#747]
We want to create a heterogeneous cluster using a multi-arch release image, as shown below.
```
hypershift create cluster --name NAME --namespace NAMESPACE --node-pool-replicas 0 --release-image quay.io/openshift-release-dev/ocp-release-nightly:4.9.8-multi ....
```
`ocp-release-nightly:4.9.8-multi` points a multi-arch manifest of cluster-version-operator. `ProcessManifestList` is supposed to pick up an architecture-specific manifest from the multi-arch one when the release image is multi-arch (i.e. `srcManifest` is a `DeserializedManifestList`). The current code picks it up only when `srcManifest` contains one architecture (i.e. the length of `srcManifests` is 1), as shown below.

https://github.com/openshift/hypershift/blob/58cabbac00c541b55c7e7925fe7e46f0a55b5ceb/support/thirdparty/oc/pkg/cli/image/manifest/manifest.go#L164-L197

Since `ocp-release-nightly:4.9.8-multi` contains a manifest of four architectures (amd64, arm64, ppc64le, and s390x), `ProcessManifestList` currently falls back and doesn't pick an architecture-specific manifest.

**Comment by hbrueckner** [comment]
@moriohara I think this is being corrected with https://github.com/openshift/hypershift/commit/9dcf50e7438961c5e482fcd1665082ff98f06481

**Comment by moriohara** [comment]
Closing this since this was fixed by https://github.com/openshift/hypershift/commit/9dcf50e7438961c5e482fcd1665082ff98f06481.
